// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0nOAZTOzPXoUeLiLjJuniM_eASFip9zM',
    appId: '1:562291678189:web:ea59c94ad7cef0d34fe5e4',
    messagingSenderId: '562291678189',
    projectId: 'bmll-c3cbe',
    authDomain: 'bmll-c3cbe.firebaseapp.com',
    storageBucket: 'bmll-c3cbe.appspot.com',
    measurementId: 'G-H55C6VK64Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUTrS63xc_ATf57OFK98MsXjfqgJIwdWw',
    appId: '1:562291678189:android:d4ab347b5e5a87e04fe5e4',
    messagingSenderId: '562291678189',
    projectId: 'bmll-c3cbe',
    storageBucket: 'bmll-c3cbe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnN6Skuy-n78f5TWWR8c2MUjEfm2RAycI',
    appId: '1:562291678189:ios:bcafe487aa37ce6c4fe5e4',
    messagingSenderId: '562291678189',
    projectId: 'bmll-c3cbe',
    storageBucket: 'bmll-c3cbe.appspot.com',
    iosBundleId: 'com.example.untitled5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnN6Skuy-n78f5TWWR8c2MUjEfm2RAycI',
    appId: '1:562291678189:ios:bcafe487aa37ce6c4fe5e4',
    messagingSenderId: '562291678189',
    projectId: 'bmll-c3cbe',
    storageBucket: 'bmll-c3cbe.appspot.com',
    iosBundleId: 'com.example.untitled5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKkYCg2pwbZoEo6oqeUnQ6R-c7gFuSclg',
    appId: '1:562291678189:web:bc619c674c3e40984fe5e4',
    messagingSenderId: '562291678189',
    projectId: 'bmll-c3cbe',
    authDomain: 'bmll-c3cbe.firebaseapp.com',
    storageBucket: 'bmll-c3cbe.appspot.com',
    measurementId: 'G-SPY4BQX7G3',
  );

}